import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

export async function businessFlows(page, project) {
  const catalogue = JSON.parse(await readFile(resolve(project, 'public/data/catalog.json'), 'utf8'));
  const current = catalogue.releases.find(r => r.id === catalogue.default_id);
  const older = catalogue.releases.find(r => r.id !== current.id);
  const original = await readFile(resolve(project, 'public/data/research.atlas.json'), 'utf8');
  const source = JSON.parse(JSON.parse(original).business.content);
  const holmen = source.companies['102'];
  const number = n => new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(n);
  const selectRelease = async release => {
    await page.getByLabel('Open data library').click();
    if (await page.locator('.app').getAttribute('data-active-release') !== release.id) await page.getByLabel(`Use release ${release.as_of}`, { exact: true }).click();
    await page.locator(`[data-active-release="${release.id}"]`).waitFor();
    await page.keyboard.press('Escape');
  };
  await selectRelease(current);
  await page.getByLabel('Observatory', { exact: true }).selectOption('sectors');
  await page.locator('[data-business-ready="true"]').waitFor();
  await page.getByLabel('Company listing country', { exact: true }).selectOption('SE');
  await page.getByLabel('Branch overview', { exact: true }).click();
  assert.equal(await page.getByLabel('Fundamentals', { exact: true }).count(), 0);
  assert.match(await page.locator('.business-heading').innerText(), /Materials[\s\S]*Forest & Wood Products/);
  await page.screenshot({ path: resolve(project, 'test-results/forestry.png') });
  await page.getByLabel('Open Holmen', { exact: true }).click();
  await page.locator('[data-company="102"][data-business-ready="true"]').waitFor();
  assert.equal(await page.getByLabel('Observatory', { exact: true }).inputValue(), 'companies');
  assert.match(await page.locator('.period-overview').innerText(), /FY 2025[\s\S]*Q1 2026/);
  assert.match(await page.locator('[data-financial="revenues"]').innerText(), new RegExp(number(holmen.annual.at(-1).values.revenues)));
  assert.match(await page.locator('.business-map-bottom').innerText(), /no good\/bad rating[\s\S]*physical resources have not been mapped/);
  await page.screenshot({ path: resolve(project, 'test-results/holmen-financials.png') });
  await page.getByRole('button', { name: 'Quarterly', exact: true }).click();
  assert.match(await page.locator('[data-financial="revenues"]').innerText(), new RegExp(number(holmen.quarterly.at(-1).values.revenues)));
  await page.getByLabel('Company financial chart', { exact: true }).selectOption('return_on_capital');
  assert.match(await page.locator('.business-content').innerText(), /No comparable saved observations/);
  await page.getByRole('button', { name: 'Annual', exact: true }).click();
  await page.getByRole('img', { name: 'Holmen Return on capital (proxy) annual history', exact: true }).waitFor();
  await page.getByLabel('Company peers', { exact: true }).click();
  assert.equal(await page.locator('[data-peer]').count(), 5);
  const annual = holmen.annual.at(-1);
  const expectedMargin = new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(100 * annual.raw.operating_income / annual.raw.revenues);
  assert.match(await page.locator('[data-peer="102"]').innerText(), new RegExp(`${expectedMargin}%`));
  assert.match(await page.locator('.business-content').innerText(), /FY 2025[\s\S]*matching full-year dates/);
  await page.screenshot({ path: resolve(project, 'test-results/forestry-peers.png') });
  await page.getByLabel('Company research', { exact: true }).click();
  await page.getByText('Holmen deep dive', { exact: false }).first().click();
  assert.match(await page.locator('.study-list').innerText(), /2026-05-21[\s\S]*2025-06-20/);
  assert.ok(await page.locator('.study-list pre').first().innerText());
  await page.getByLabel('Search companies or countries').fill('Stora');
  await page.getByLabel('Search companies or countries').press('Enter');
  await page.locator('[data-company="696"][data-business-ready="true"]').waitFor();
  assert.match(await page.locator('.business-heading').innerText(), /Finland[\s\S]*EUR reporting currency/);
  await page.getByLabel('Company macro context', { exact: true }).click();
  assert.match(await page.locator('.business-content').innerText(), /No Finland country profile/);
  await page.getByRole('button', { name: 'Open Finland in Macro', exact: true }).click();
  assert.equal(await page.locator('.sidebar').getAttribute('data-country'), 'FI');
  await page.locator('[data-country-evidence="FI"][data-evidence-ready="true"]').waitFor();
  assert.match(await page.locator('.sidebar').innerText(), /Finland · assessment & monitoring/);
  assert.equal(await page.locator('.sidebar [data-signal]').count(), 4);
  await page.locator('[data-map-ready="true"]').waitFor();
  await page.waitForTimeout(800);
  assert.equal(await page.locator('.map-error').count(), 0);
  await page.screenshot({ path: resolve(project, 'test-results/finland-macro-map.png') });
  // Keep the uncovered-country case with a real map country absent from both
  // independent country evidence and legacy fundamentals. Exercise reopening a
  // persisted selection; neither a company nor another country's data may leak in.
  const evidence = JSON.parse(await readFile(resolve(project, 'public/data/country-evidence/index.json'), 'utf8'));
  const world = JSON.parse(await readFile(resolve(project, 'public/maps/world.geojson'), 'utf8'));
  assert.ok(world.features.some(f => f.properties.code === 'DZ'));
  assert.equal(evidence.countries.DZ, undefined);
  await page.evaluate(() => {
    const preferences = JSON.parse(localStorage.getItem('atlas.preferences') ?? '{}');
    localStorage.setItem('atlas.preferences', JSON.stringify({ ...preferences, code: 'DZ', observatory: 'macro' }));
  });
  await page.reload();
  await page.locator('[data-country="DZ"] .uncovered').waitFor();
  assert.match(await page.locator('.sidebar').innerText(), /no data in the current release/);
  assert.equal(await page.locator('[data-country-evidence]').count(), 0);
  await page.getByLabel('Search countries').fill('Sweden');
  await page.getByLabel('Search countries').press('Enter');
  await page.getByLabel('Observatory', { exact: true }).selectOption('companies');
  await page.getByLabel('Search companies or countries').fill('Holmen');
  await page.getByLabel('Search companies or countries').press('Enter');
  await page.locator('[data-company="102"][data-business-ready="true"]').waitFor();
  // Changing releases cannot leave a newer company or stale country visible.
  await selectRelease(older);
  await page.getByRole('heading', { name: 'No company research in this release', exact: true }).waitFor();
  assert.equal(await page.locator('[data-financial]').count(), 0);
  await page.getByLabel('Open data library').click();
  const damaged = JSON.parse(original); damaged.business.content = '{}';
  await page.getByLabel('Research file', { exact: true }).setInputFiles({ name: 'damaged-business.atlas.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(damaged)) });
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').innerText(), /checksum/);
  await page.getByLabel('Research file', { exact: true }).setInputFiles({ name: 'companies.atlas.json', mimeType: 'application/json', buffer: Buffer.from(original) });
  await page.getByRole('button', { name: 'Import and use', exact: true }).click();
  await page.locator(`[data-release-id="${current.id}"][data-storage="imported"]`).waitFor();
  await page.keyboard.press('Escape');
  await page.locator('[data-company="102"][data-business-ready="true"]').waitFor();
  await page.reload();
  await page.locator(`[data-active-release="${current.id}"] [data-company="102"][data-business-ready="true"]`).waitFor();
  assert.match(await page.locator('[data-financial="revenues"]').innerText(), new RegExp(number(holmen.annual.at(-1).values.revenues)));
  assert.equal(await page.getByLabel('Observatory', { exact: true }).inputValue(), 'companies');
  return { current, original, checks: ['Contextual observatory menus and Sweden → forestry → Holmen', 'Annual and quarterly financial periods', 'Annual-only return proxy and matching peer ratios', 'Neutral coverage and comparison colours', 'Dated archived deep dive', 'Company opens Finland independent macro evidence and map', 'Uncovered Algeria selection stays empty after reopening', 'Old releases cannot show newer business data', 'Damaged company document rejected', 'V3 company import and selected observatory persist after reload'] };
}
