import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';

export async function taxonomyFlows(page, project) {
  const original = await readFile(resolve(project, 'public/data/research.atlas.json'), 'utf8');
  const payload = JSON.parse(original), taxonomy = JSON.parse(payload.taxonomy.content);
  const catalogue = JSON.parse(await readFile(resolve(project, 'public/data/catalog.json'), 'utf8'));
  const current = catalogue.releases.find(r => r.id === catalogue.default_id);
  const listings = Object.values(taxonomy.catalogue.listings);
  const countryCount = (branch, country) => listings.filter(c => taxonomy.classifications[c.id].branch_id === branch && c.listing_country === country).length;
  await page.getByLabel('Observatory', { exact: true }).selectOption('sectors');
  await page.locator('[data-taxonomy-ready="true"]').waitFor();
  await page.getByLabel('Company listing country', { exact: true }).selectOption('SE');
  assert.equal(await page.locator('.branch-choice').count(), 94);
  assert.equal(await page.locator('.sector-group').count(), 10);
  assert.match(await page.getByLabel('Directory coverage').innerText(), /10[\s\S]*94[\s\S]*17[\s\S]*89/);
  await page.screenshot({ path: resolve(project, 'test-results/sector-directory.png') });
  await page.getByLabel('Filter branch coverage').selectOption('studies');
  assert.equal(await page.locator('.branch-choice').count(), 17);
  await page.getByLabel('Filter branch coverage').selectOption('profiles');
  assert.equal(await page.locator('.branch-choice').count(), 1);
  assert.match(await page.locator('.branch-choice').innerText(), /5 research profiles/);
  await page.getByLabel('Filter branch coverage').selectOption('all');
  await page.getByLabel('Filter sectors', { exact: true }).selectOption('7');
  assert.equal(await page.locator('.branch-choice').count(), Object.values(taxonomy.branches).filter(b => b.sector_id === '7').length);
  await page.getByLabel('Filter sectors', { exact: true }).selectOption('all');
  const search = page.getByLabel('Search sectors and branches', { exact: true });
  await search.fill('skogsbolag');
  assert.equal(await page.locator('.branch-choice').count(), 1);
  assert.match(await page.locator('.branch-choice').innerText(), /Forest & Wood Products/);
  await search.fill('Biotechnology');
  const biotech = Object.values(taxonomy.branches).find(b => b.name_en === 'Biotechnology');
  assert.ok(biotech);
  await page.locator(`.branch-choice[data-branch="${biotech.id}"]`).click();
  await page.locator(`.business-sidebar[data-branch="${biotech.id}"]`).waitFor();
  assert.match(await page.locator('.business-heading').innerText(), /Biotechnology/);
  assert.match(await page.locator('.branch-coverage').innerText(), /Pending/);
  assert.equal(await page.getByLabel('Open Holmen', { exact: true }).count(), 0);
  assert.equal(await page.getByLabel('Forestry value chain').count(), 0);
  assert.equal(Number(await page.locator('[data-country-listing-count]').getAttribute('data-country-listing-count')), countryCount(biotech.id, 'SE'));
  assert.ok(await page.locator('.company-list [data-listing]').count() > 0);
  assert.equal(await page.locator('.coverage-grid strong').last().innerText(), '1136');
  await page.getByLabel('Branch macro context', { exact: true }).click();
  assert.match(await page.locator('.business-content').innerText(), /Branch context is not included yet/);
  assert.equal(await page.locator('.macro-observation').count(), 0);
  await page.getByLabel('Branch research', { exact: true }).click();
  assert.match(await page.locator('.branch-inventory').innerText(), /Research in your project/);
  assert.equal(await page.locator('.study-list').count(), 0);
  await page.getByLabel('Branch overview', { exact: true }).click();
  await page.screenshot({ path: resolve(project, 'test-results/branch-pending.png') });
  // Branch choice persists even with no company profile in that branch.
  await page.reload();
  await page.locator('[data-taxonomy-ready="true"]').waitFor();
  await page.getByLabel('Branch overview', { exact: true }).click();
  assert.equal(await page.locator('.business-sidebar').getAttribute('data-branch'), biotech.id);
  await page.getByLabel('Browse sectors and branches', { exact: true }).click();
  await search.fill('Forsakring'); // Accent-insensitive Swedish search.
  assert.ok(await page.locator('.branch-choice').count() > 0);
  const beer = taxonomy.branches['58'];
  await search.fill(beer.name_sv);
  await page.locator('.branch-choice[data-branch="58"]').click();
  assert.match(await page.locator('.branch-coverage').innerText(), /Shared research also covers/);
  await page.getByLabel('Branch research', { exact: true }).click();
  assert.equal(await page.locator('.dive-inventory > details').count(), new Set([...beer.deep_dives, ...beer.shared_study_ids.flatMap(id => taxonomy.shared_studies[id].deep_dives)].map(d => d.folder)).size);
  await page.getByLabel('Search companies or countries').fill('Holmen');
  await page.getByLabel('Search companies or countries').press('Enter');
  await page.locator('[data-company="102"][data-branch="21"][data-business-ready="true"]').waitFor();
  await page.locator('.classification-details summary').click();
  assert.match(await page.locator('.classification-details').innerText(), /Börsdata default[\s\S]*sector 7, branch 21/);
  await page.getByLabel('Choose a sector or branch').click();
  await page.locator('.branch-choice[data-branch="21"][aria-pressed="true"]').waitFor();
  await page.setViewportSize({ width: 1100, height: 760 });
  await page.screenshot({ path: resolve(project, 'test-results/directory-compact.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  await page.setViewportSize({ width: 1500, height: 960 });

  // A real v2 package has the same financial bytes but no taxonomy resource.
  const legacy = structuredClone(payload); delete legacy.taxonomy; legacy.schema_version = 2;
  const legacyText = JSON.stringify(legacy);
  const legacyId = createHash('sha256').update(`macro-atlas-research-v2\n${legacy.fundamentals.sha256}\n${legacy.liquidity?.sha256 ?? ''}\n${legacy.business.sha256}`).digest('hex');
  await page.getByLabel('Open data library').click();
  const input = page.getByLabel('Research file', { exact: true });
  const damaged = structuredClone(payload); damaged.taxonomy.content = '{}';
  await input.setInputFiles({ name: 'damaged-taxonomy.atlas.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(damaged)) });
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').innerText(), /checksum/);
  const badBinding = structuredClone(payload), mismatched = structuredClone(taxonomy);
  mismatched.business_sha256 = 'a'.repeat(64);
  badBinding.taxonomy.content = JSON.stringify(mismatched);
  badBinding.taxonomy.sha256 = createHash('sha256').update(badBinding.taxonomy.content).digest('hex');
  await input.setInputFiles({ name: 'mismatched-taxonomy.atlas.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(badBinding)) });
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').innerText(), /does not match the selected business document/);
  // A synthetic correction is used only inside this isolated test archive.
  const reviewed = structuredClone(payload), corrected = structuredClone(taxonomy);
  corrected.classifications['102'] = { ...corrected.classifications['102'], sector_id: biotech.sector_id, branch_id: biotech.id, status: 'corrected', correction: { company_id: '102', expected_sector_id: '7', expected_branch_id: '21', branch_id: biotech.id, reason: 'Isolated navigation test; not a real company classification.', source: 'Synthetic test fixture', reviewed_at: taxonomy.as_of } };
  reviewed.taxonomy.content = JSON.stringify(corrected);
  reviewed.taxonomy.sha256 = createHash('sha256').update(reviewed.taxonomy.content).digest('hex');
  await input.setInputFiles({ name: 'synthetic-review.atlas.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(reviewed)) });
  await page.getByRole('button', { name: 'Import and use', exact: true }).click();
  await page.getByText('Research saved and opened.', { exact: true }).waitFor();
  await page.keyboard.press('Escape');
  await page.locator('[data-taxonomy-ready="true"]').waitFor();
  await search.fill('Biotechnology');
  await page.locator(`.branch-choice[data-branch="${biotech.id}"]`).click();
  assert.equal(Number(await page.locator('[data-country-listing-count]').getAttribute('data-country-listing-count')), countryCount(biotech.id, 'SE') + 1);
  await page.getByLabel('Open Holmen', { exact: true }).click();
  await page.locator(`[data-company="102"][data-branch="${biotech.id}"][data-business-ready="true"]`).waitFor();
  await page.locator('.classification-details summary').click();
  assert.match(await page.locator('.classification-details').innerText(), /Reviewed correction[\s\S]*sector 7, branch 21[\s\S]*Biotechnology/);
  await page.getByLabel('Open data library').click();
  await input.setInputFiles({ name: 'legacy-companies.atlas.json', mimeType: 'application/json', buffer: Buffer.from(legacyText) });
  await page.getByRole('button', { name: 'Import and use', exact: true }).click();
  await page.locator(`[data-active-release="${legacyId}"]`).waitFor();
  await page.keyboard.press('Escape');
  await page.getByLabel('Observatory', { exact: true }).selectOption('sectors');
  await page.getByRole('heading', { name: 'No full branch directory in this release', exact: true }).waitFor();
  assert.equal(await page.locator('.branch-choice').count(), 0);
  await page.getByRole('button', { name: 'Open saved branch', exact: true }).click();
  await page.getByLabel('Open Holmen', { exact: true }).click();
  await page.locator('[data-company="102"][data-business-ready="true"]').waitFor();
  assert.match(await page.locator('.period-overview').innerText(), /FY 2025/);
  await page.getByLabel('Open data library').click();
  await page.locator(`[data-release-id="${current.id}"] button`).click();
  await page.locator(`[data-active-release="${current.id}"]`).waitFor();
  await page.keyboard.press('Escape');
  await page.locator('[data-company="102"][data-business-ready="true"]').waitFor();
  await page.reload();
  await page.locator(`[data-active-release="${current.id}"] [data-company="102"][data-branch="21"][data-business-ready="true"]`).waitFor();
  return { legacyId, legacyText, checks: ['All 10 sectors and 94 branches; separate 17-study/89-dossier coverage', 'Swedish, English and accent-insensitive search; sector and coverage filters', 'Unresearched branch has its own company listings and counts without inheriting forestry context or prose', 'Branch selection survives reload', 'Shared study inventory is deduplicated', 'Company selection restores branch and source classification', 'Compact directory has no horizontal overflow', 'Taxonomy checksum and business binding failures rejected', 'Reviewed correction changes branch coverage while preserving original IDs', 'V2 import remains usable and cannot inherit V3 taxonomy', 'V3 directory and company selection survive reload'] };
}
