import { useState } from 'react';
import { financialSeries, formulas, periodLabel, ratioLabels } from './business';
import { format, seriesColors } from './model';
import { hasFinancialHistory, statementLabels, type CompanyCoverage, type FinancialCompany, type FinancialIndex } from './financialData';
import type { CompanyEntry } from './listingCatalogue';
import FinancialChart from './FinancialChart';

const count = (n: number) => n.toLocaleString('en-US');
const statements = {
  income: { label: 'Income statement', fields: ['revenues', 'net_sales', 'gross_income', 'operating_income', 'profit_before_tax', 'profit_to_equity_holders'] },
  balance: { label: 'Balance sheet', fields: ['total_assets', 'non_current_assets', 'intangible_assets', 'tangible_assets', 'financial_assets', 'current_assets', 'cash_and_equivalents', 'total_equity', 'non_current_liabilities', 'current_liabilities', 'total_liabilities_and_equity', 'net_debt'] },
  cash: { label: 'Cash flow', fields: ['cash_flow_from_operating_activities', 'cash_flow_from_investing_activities', 'cash_flow_from_financing_activities', 'cash_flow_for_the_year', 'free_cash_flow'] },
};
export default function FinancialHistory({ entry, index, company }: { entry: CompanyEntry; index: FinancialIndex; company: FinancialCompany }) {
  const coverage = index.companies[entry.id];
  const [frequency, setFrequency] = useState<'annual' | 'quarterly'>(coverage.annual.count ? 'annual' : 'quarterly');
  const [metric, setMetric] = useState('revenues'), [statement, setStatement] = useState<keyof typeof statements>('income');
  const [chosenCurrency, setChosenCurrency] = useState(''), [period, setPeriod] = useState('');
  const reports = company[frequency], latest = reports.at(-1), annual = company.annual.at(-1), quarter = company.quarterly.at(-1);
  const currency = chosenCurrency || latest?.currency || coverage.currencies[0] || entry.report_currency || '';
  const selected = reports.find(r => `${r.year}-${r.period}` === period) ?? latest;
  const labels = { ...statementLabels, ...ratioLabels }, series = financialSeries(reports, metric, currency);
  const unit = metric in ratioLabels ? '%' : `${currency} million`;
  return <div className="company-financial-history" data-financial-history={entry.id} data-financial-pack={index.id}>
    <section><div className="section-title"><h3>Saved report coverage</h3><span className="micro">{index.as_of}</span></div><CoverageDetails coverage={coverage} />
      <p className="chart-caption">Coverage describes saved reports. Missing periods and unavailable values stay blank; a download date is not a financial period.</p>
      {coverage.withheld > 0 && <p className="financial-quality-note">{count(coverage.withheld)} source {coverage.withheld === 1 ? 'row withheld' : 'rows withheld'} because the period, date or currency metadata could not be used. See the source notes below.</p>}
    </section>
    {hasFinancialHistory(coverage) ? <>
      <section><div className="period-overview"><div><small>LATEST FULL YEAR</small><strong>{annual ? periodLabel(annual) : 'Unavailable'}</strong><span>Reported {annual?.report_date ?? 'date unavailable'}</span></div><div><small>LATEST SAVED QUARTER</small><strong>{quarter ? periodLabel(quarter) : 'Unavailable'}</strong><span>Reported {quarter?.report_date ?? 'date unavailable'}</span></div></div></section>
      <section><div className="section-title"><h3>Financial history</h3><div className="frequency-buttons" role="group" aria-label="Financial reporting frequency"><button aria-pressed={frequency === 'annual'} onClick={() => { setFrequency('annual'); setPeriod(''); }}>Annual</button><button aria-pressed={frequency === 'quarterly'} onClick={() => { setFrequency('quarterly'); setPeriod(''); }}>Quarterly</button></div></div>
        <p className="business-note">{latest ? `${periodLabel(latest)} · ${latest.start} to ${latest.end} · ${latest.currency} million · saved ${latest.source_as_of}` : 'No saved reports for this frequency.'}</p>
        <div className="financial-cards">{['revenues', 'operating_income', 'free_cash_flow', 'net_debt'].map(key => <div key={key} data-financial={key}><small>{statementLabels[key]}</small><strong>{format(latest?.values[key], 0)}</strong><span>{latest?.currency ?? currency} million</span></div>)}</div>
        <select className="metric-select" aria-label="Company financial chart" value={metric} onChange={e => setMetric(e.target.value)}>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>
        {coverage.currencies.length > 1 && <label className="statement-control">Chart reporting currency<select aria-label="Chart reporting currency" value={currency} onChange={e => setChosenCurrency(e.target.value)}>{coverage.currencies.map(c => <option key={c}>{c}</option>)}</select></label>}
        <FinancialChart labels={series.labels} series={[{ name: labels[metric], values: series.values, color: seriesColors.selected }]} label={`${entry.display_name} ${labels[metric]} ${frequency} history`} unit={unit} />
        <p className="chart-caption">{unit}. {formulas[metric] ?? 'Nominal reported amounts, recovered using each row’s saved currency conversion.'} Missing periods stay blank. {frequency === 'quarterly' && 'Flows cover individual quarters; balances are at period end. The return proxy is annual only.'} {coverage.currencies.length > 1 && 'Monetary charts show one reporting currency at a time; ratios are dimensionless.'}</p>
        <details className="financial-table"><summary>View financial figures</summary><div className="table-scroll"><table><thead><tr><th>Period</th><th>Currency</th><th>{labels[metric]}</th><th>Reported</th><th>Saved</th></tr></thead><tbody>{[...reports].reverse().map(r => <tr key={`${r.year}-${r.period}`}><td>{periodLabel(r)}</td><td>{metric in ratioLabels ? '%' : `${r.currency} m`}</td><td>{format(r.values[metric], 2)}</td><td>{r.report_date ?? 'Unknown'}</td><td>{r.source_as_of}</td></tr>)}</tbody></table></div></details>
      </section>
      <section className="financial-statements"><h3>Financial statements</h3><div className="statement-tabs" role="group" aria-label="Financial statement">{Object.entries(statements).map(([key, value]) => <button key={key} aria-pressed={statement === key} onClick={() => setStatement(key as keyof typeof statements)}>{value.label}</button>)}</div>
        <label className="statement-control">{frequency === 'annual' ? 'Financial year' : 'Financial quarter'}<select aria-label="Statement period" value={selected ? `${selected.year}-${selected.period}` : ''} onChange={e => setPeriod(e.target.value)} disabled={!reports.length}>{[...reports].reverse().map(r => <option key={`${r.year}-${r.period}`} value={`${r.year}-${r.period}`}>{periodLabel(r)} · {r.currency} · ends {r.end}</option>)}{!reports.length && <option value="">No saved periods</option>}</select></label>
        {selected ? <><p className="chart-caption">{selected.start} to {selected.end} · published {selected.report_date ?? 'date unavailable'} · saved {selected.source_as_of}. Amounts in {selected.currency} million.</p><table className="statement-table" aria-label={`${statements[statement].label} figures`}><tbody>{statements[statement].fields.map(key => <tr key={key} data-statement-field={key}><th>{statementLabels[key]}</th><td>{format(selected.values[key], 2)}</td></tr>)}</tbody></table>
          <p className="chart-caption">Source fields are shown as provided. Missing values are not zero. {statement === 'balance' && 'Asset categories can overlap; net debt is a supplementary measure. These figures do not identify individual properties or facilities.'}{statement === 'income' && 'Revenue and net sales are separate provider fields and must not be added together.'}{statement === 'cash' && 'Börsdata FCF uses the provider’s definition; it does not deduct lease principal and interest and is not owner earnings.'}</p>
          <details className="financial-table"><summary>Inspect saved amounts and conversion</summary><p className="business-note">The source stores monetary amounts after multiplying by its currency ratio. Atlas divides each amount by that same ratio to recover {selected.currency} millions. Saved ratio: {selected.currency_ratio ?? 'unavailable'}. A missing or non-positive ratio leaves all converted values unavailable.</p><div className="table-scroll"><table><thead><tr><th>Field</th><th>Saved amount</th><th>{selected.currency} million</th></tr></thead><tbody>{statements[statement].fields.map(key => <tr key={key}><td>{statementLabels[key]}</td><td>{format(selected.raw[key], 4)}</td><td>{format(selected.values[key], 4)}</td></tr>)}</tbody></table></div></details></> : <p className="empty">No saved statements for this frequency.</p>}
      </section>
      <section><h3>Profitability through the cycle</h3><FinancialChart labels={financialSeries(company.annual, 'operating_margin', currency).labels} series={['operating_margin', 'return_on_capital'].map((key, i) => ({ name: ratioLabels[key], values: financialSeries(company.annual, key, currency).values, color: i ? seriesColors.comparison : seriesColors.selected }))} label={`${entry.display_name} annual operating margin and return on capital proxy`} unit="%" /><p className="business-note">Reported profit may include revaluations or one-off transactions. The annual return proxy uses year-end equity plus net debt; it is not adjusted ROIC. These ratios have different relevance across branches, particularly financial businesses.</p></section>
    </> : <section><h3>No usable saved reports</h3><p className="business-note">No annual or quarterly reports could be shown for this listing from the two saved downloads. Its company and branch details remain available.</p></section>}
    <section><h3>Sources and interpretation</h3><p className="business-note">The newest saved row takes precedence for each fiscal period. Earlier periods can come from an older download and may use a different accounting or restatement basis. Invalid newer rows are withheld; an older value is not silently substituted.</p><p className="business-note">Amounts are nominal. Börsdata FCF does not deduct lease principal and interest. Per-share figures are omitted here because the saved files can use different split-adjustment bases.</p>
      {company.withheld.length > 0 && <details className="withheld-reports"><summary>{count(company.withheld.length)} withheld source rows</summary><div className="table-scroll"><table><thead><tr><th>Fiscal period</th><th>Saved</th><th>Source dates</th><th>Reason</th></tr></thead><tbody>{company.withheld.map((r, i) => <tr key={i}><td>{r.period === 5 ? 'FY' : `Q${r.period}`} {r.year}</td><td>{index.sources.find(s => s.id === r.source_id)?.as_of}</td><td>{r.start} – {r.end}<br />Published {r.published}</td><td>{r.reason}</td></tr>)}</tbody></table></div></details>}
      <details className="business-sources"><summary>Financial source register</summary>{index.sources.map(source => <dl key={source.id}><dt>{source.frequency} · saved {source.as_of}</dt><dd>{source.path}</dd><dd className="hash">SHA-256 {source.sha256}</dd></dl>)}<p className="chart-caption">Financial pack {index.id.slice(0, 12)} · {count(index.summary.annual)} annual and {count(index.summary.quarterly)} quarterly reports. The library can save a separate copy for backup or another offline computer.</p></details>
    </section>
  </div>;
}
function CoverageDetails({ coverage }: { coverage: CompanyCoverage }) {
  return <div className="financial-coverage">{(['annual', 'quarterly'] as const).map(frequency => { const c = coverage[frequency]; return <div key={frequency} data-coverage={frequency}><small>{frequency.toUpperCase()} REPORTS</small><strong>{count(c.count)}</strong><span>{c.count ? `${c.first}–${c.last}${frequency === 'quarterly' ? ` · latest Q${c.last_period}` : ''}` : 'No saved periods'}</span><span>{c.gaps} missing {frequency === 'annual' ? 'years' : 'quarters'} within span</span>{c.end && <span>Latest period ends {c.end}</span>}{c.unavailable > 0 && <span>{c.unavailable} reports without usable amounts</span>}</div>; })}</div>;
}
