import { ArrowRight, ClipboardList } from 'lucide-react';
import type { ResearchGaugeArtifact, ResearchGaugePeriod, ResearchGaugeReadiness, ResearchGaugeRoute, ResearchGaugeRow, ResearchGaugeSeries } from './researchGaugeModel';
import './researchGauge.css';

export const researchRouteLabels: Record<ResearchGaugeRoute, string> = {
  operating: 'Operating business', property: 'Property research', financial: 'Financial business', unclassified: 'Classification review',
};
export const researchReadinessLabels: Record<ResearchGaugeReadiness, string> = {
  history_available: 'Five-period evidence', limited_history: 'Limited or older evidence', reconcile_data: 'Reconcile data first', no_history: 'No annual history',
};
export const researchNumber = (value: number | null | undefined, digits = 2) => value === null || value === undefined || !Number.isFinite(value) ? 'Unavailable' : value.toLocaleString('en-US', value !== 0 && Math.abs(value) < 10 ** -digits ? { maximumSignificantDigits: 3 } : { maximumFractionDigits: digits });
export const researchPercent = (value: number | null | undefined, digits = 1) => value === null || value === undefined ? 'Unavailable' : `${researchNumber(value, digits)}%`;
export const researchPeriod = (period: ResearchGaugePeriod | null | undefined) => period ? period.period === 5 ? `FY ${period.year}` : `Q${period.period} ${period.year}` : 'No saved period';
export const researchPositive = (series: ResearchGaugeSeries) => series.count ? `${series.positive} / ${series.count} positive` : 'Unavailable';
const amount = (value: number | null, currency: string | null) => value === null ? 'Unavailable' : `${researchNumber(value)} ${currency ?? 'currency unavailable'} m`;

export function researchQuestions(row: ResearchGaugeRow): string[] {
  const questions: string[] = [];
  if (row.route === 'financial') questions.push('Review regulatory capital and distributions using a financial-business model.');
  else if (row.route === 'property') questions.push('Reconcile recurring property cash, maintenance investment and financing.');
  else if (row.route === 'unclassified' || row.classificationConflict) questions.push('Establish the business classification and appropriate research method.');
  if (!row.annual.periods.length) questions.push(row.annual.reason ?? 'Reconcile missing annual evidence before comparing the business.');
  else if (row.annual.cash.negative) questions.push(`Explain ${row.annual.cash.negative} negative provider FCF observation${row.annual.cash.negative === 1 ? '' : 's'} and the associated funding needs.`);
  else if (row.annual.cash.count) questions.push('Check how much recorded cash remains after maintenance investment, leases and ownership adjustments.');
  else questions.push('Provider FCF is unavailable in the comparable annual window.');
  if (row.annual.ebit.negative) questions.push('Separate cyclical operating losses from persistent business problems.');
  else if (row.annual.ebit.count) questions.push('Investigate whether historical profitability can persist through a full cycle.');
  return questions;
}

function PeriodDetails({ period, label }: { period: ResearchGaugePeriod | null; label: string }) {
  return <div><h4>{label}</h4>{period ? <><p>{researchPeriod(period)} · {period.start} to {period.end} · {period.currency}</p><p>Published {period.published ?? 'date unavailable'} · source saved {period.sourceAsOf}</p><p className="hash">Source {period.sourceId}</p></> : <p>No retained report is available.</p>}</div>;
}

export function ResearchGaugeEvidence({ row, data, showValuation = false }: { row: ResearchGaugeRow; data: ResearchGaugeArtifact; showValuation?: boolean }) {
  const annual = row.annual, quarter = row.quarter, values = annual.latestValues, valuation = row.valuation;
  const metrics: [string, ResearchGaugeSeries, string][] = [['Provider FCF', annual.cash, annual.currency ?? 'Unknown currency'], ['Operating cash flow', annual.operatingCash, annual.currency ?? 'Unknown currency'], ['EBIT', annual.ebit, annual.currency ?? 'Unknown currency'], ['Revenue', annual.revenue, annual.currency ?? 'Unknown currency'], ['EBIT margin', annual.margins, '%']];
  return <div className="research-gauge-evidence" data-research-evidence={row.id}>
    <p><strong>{researchReadinessLabels[row.readiness]}</strong> · {researchRouteLabels[row.route]}. This describes evidence coverage and the research route.</p>
    <ul className="research-gauge-reasons">{researchQuestions(row).map(question => <li key={question}>{question}</li>)}</ul>
    {!!row.issues.length && <><h4>Data and interpretation notes</h4><ul className="research-gauge-reasons">{row.issues.map(issue => <li key={issue}>{issue}</li>)}</ul></>}
    <h4>Comparable annual history</h4>
    <p>Up to five consecutive annual periods, newest first. Counts use valid observations for each measure; missing values stay unavailable. EBIT margin = EBIT ÷ positive revenue × 100.</p>
    <div className="table-scroll" tabIndex={0} role="region" aria-label={`${row.name} annual research figures`}><table><thead><tr><th scope="col">Measure</th><th scope="col">Positive / valid</th><th scope="col">Missing / periods</th><th scope="col">Latest</th><th scope="col">Median</th></tr></thead><tbody>{metrics.map(([label, series, unit]) => <tr key={label}><th scope="row">{label}<small>{unit === '%' ? '%' : `${unit} million`}</small></th><td>{series.count ? `${series.positive} / ${series.count}` : 'Unavailable'}</td><td>{annual.periods.length - series.count} / {annual.periods.length}</td><td>{researchNumber(series.latest)}</td><td>{researchNumber(series.median)}</td></tr>)}</tbody></table></div>
    <p>Provider FCF dispersion: {researchNumber(annual.cash.dispersion)}. Formula: population standard deviation of signed cash ÷ mean absolute cash, with at least two observations and a positive scale. It describes this window; it is not a forecast probability.</p>
    <div className="table-scroll" tabIndex={0} role="region" aria-label={`${row.name} annual research periods`}><table><thead><tr><th scope="col">Fiscal period</th><th scope="col">Dates</th><th scope="col">Provider FCF</th><th scope="col">Operating cash flow</th><th scope="col">EBIT</th><th scope="col">Revenue</th><th scope="col">EBIT margin</th><th scope="col">Published / saved</th></tr></thead><tbody>{annual.periods.map((period, i) => <tr key={`${period.year}:${period.end}`}><th scope="row">{researchPeriod(period)}<small>{period.currency} m</small></th><td>{period.start}<br />{period.end}</td><td>{researchNumber(annual.cash.values[i])}</td><td>{researchNumber(annual.operatingCash.values[i])}</td><td>{researchNumber(annual.ebit.values[i])}</td><td>{researchNumber(annual.revenue.values[i])}</td><td>{researchPercent(annual.margins.values[i])}</td><td>{period.published ?? 'Publication unavailable'}<small>Saved {period.sourceAsOf}</small></td></tr>)}</tbody></table></div>
    {!annual.periods.length && <p>{annual.reason ?? 'No comparable annual window is available.'}</p>}
    <p>Annual inventory: {annual.excluded.outsideWindow} retained reports outside the selected window; {annual.excluded.placeholder} possible placeholders; {annual.excluded.missingPublication} reports without publication dates; {annual.excluded.withheld} withheld reports. These counts can overlap; a missing publication date is disclosed even when a report is included.</p>
    <div className="research-gauge-evidence-grid">
      <div><h4>Latest comparable annual financing and assets</h4><p>{researchPeriod(annual.periods[0])}. Amounts in {annual.currency ?? 'unknown currency'} million.</p><dl><dt>Cash balance</dt><dd>{researchNumber(values.cashBalance)}</dd><dt>Net debt</dt><dd>{researchNumber(values.netDebt)}</dd><dt>Financing cash flow</dt><dd>{researchNumber(values.financingCash)}</dd><dt>Total assets</dt><dd>{researchNumber(values.assets)}</dd><dt>Total equity</dt><dd>{researchNumber(values.equity)}</dd><dt>Annual revenue</dt><dd>{researchNumber(values.revenues)}</dd><dt>Net debt / total assets</dt><dd>{researchPercent(values.netDebtToAssetsPercent)}</dd><dt>Equity / total assets</dt><dd>{researchPercent(values.equityToAssetsPercent)}</dd><dt>Tangible assets / revenue</dt><dd>{values.tangibleAssetsToRevenue === null ? 'Unavailable' : `${researchNumber(values.tangibleAssetsToRevenue)}×`}</dd><dt>Intangible assets / total assets</dt><dd>{researchPercent(values.intangibleAssetsToAssetsPercent)}</dd><dt>FCF − operating cash − signed investing cash</dt><dd>{researchNumber(values.cashComponentDifference)}</dd></dl><p>Ratios require a positive denominator. Asset and financing ratios are descriptive proxies. Aggregate fields do not establish maintenance capex, debt maturities, refinancing capacity or verified tangible common equity. A cash-component difference is a reconciliation question, not proof of an error.</p></div>
      <div><h4>Latest saved quarter against the same quarter a year earlier</h4><dl><dt>Revenue change</dt><dd>{researchPercent(quarter.revenueChangePercent)}</dd><dt>EBIT margin change</dt><dd>{quarter.ebitMarginChangePoints === null ? 'Unavailable' : `${researchNumber(quarter.ebitMarginChangePoints)} percentage points`}</dd><dt>Provider FCF change</dt><dd>{amount(quarter.cashChange, quarter.latest?.currency ?? null)}</dd></dl><p>Revenue change = (latest revenue − previous revenue) ÷ positive previous revenue × 100. Cash change is an amount, so a loss-to-profit change does not produce a misleading growth percentage.</p>{quarter.reason && <p>{quarter.reason}</p>}<PeriodDetails period={quarter.latest} label="Latest retained quarter" /><PeriodDetails period={quarter.comparison} label="Comparison quarter" /></div>
    </div>
    {showValuation && <div className="research-gauge-valuation" data-research-valuation={row.id}>
      <h4>Standard starter valuation · optional research context</h4><p>This frozen starter uses saved provider FCF and explicit assumptions. A reviewed study or your edited working valuation may differ. Amounts are whole-equity {valuation.currency} million.</p>
      <dl><dt>Mid present value</dt><dd data-research-value={valuation.value ?? ''}>{researchNumber(valuation.value)}</dd><dt>Annual cash present value</dt><dd>{researchNumber(valuation.cashPV)}</dd><dt>Terminal present value</dt><dd>{researchNumber(valuation.terminalPV)}</dd><dt>Terminal contribution / Mid value</dt><dd>{valuation.terminalShare === null ? 'Unavailable' : researchPercent(valuation.terminalShare * 100)}</dd><dt>Ceiling at the fixed 30% margin</dt><dd>{researchNumber(valuation.ceiling)}</dd><dt>Saved derived equity value</dt><dd data-research-price={valuation.candidateEquity ?? ''}>{researchNumber(valuation.candidateEquity)}</dd><dt>Saved price date / age at screen snapshot</dt><dd data-research-price-date>{valuation.priceDate ?? 'Unavailable'}{valuation.priceAgeDays !== null && ` · ${researchNumber(valuation.priceAgeDays, 0)} days`}</dd><dt>Required cash level to cover saved equity value</dt><dd data-research-reverse={valuation.reverseCashFactor ?? ''}>{valuation.reverseCashFactor === null ? 'Unavailable' : `${researchNumber(valuation.reverseCashFactor)}× Mid cash`}</dd><dt>Required cash level for the 30% margin</dt><dd data-research-reverse30={valuation.reverseCashFactor30 ?? ''}>{valuation.reverseCashFactor30 === null ? 'Unavailable' : `${researchNumber(valuation.reverseCashFactor30)}× Mid cash`}</dd><dt>Low scenario present value</dt><dd>{researchNumber(valuation.lowValue)}</dd><dt>Low NPV at saved derived equity value</dt><dd>{researchNumber(valuation.lowNPV)}</dd></dl>
      {valuation.reason && <p>{valuation.reason}</p>}
      <p>V = annual cash PV + terminal PV, counted once. Ceiling = 0.70 × positive V. Required cash levels are P / V and P / (0.70 × V), where P is the saved derived equity value. Both annual cash and first post-horizon terminal cash scale together; rates and horizon stay fixed. These are required proportional cash levels, not expected growth or independent valuation confirmations.</p>
      <p>The standard starter projects ten years. Mid holds the latest eligible annual provider FCF flat; it does not extrapolate historical growth. The trailing history setting is five annual periods, with {valuation.annualHistoryCount} eligible observations for this listing. Required return starts at 10%, mature growth at 0%. First post-horizon terminal cash uses the signed history median, requiring at least three eligible periods; Low and High terminal cash subtract or add an assumed 20% of the absolute median. Nonpositive terminal cash supplies zero modeled terminal sale.</p>
      <p>{valuation.rangeStatus === 'historical' ? 'This starter uses historical-error ranges for years 1–4, with assumed widening in years 5–10.' : valuation.rangeStatus === 'percentage' ? 'Historical-error support is unavailable for this starter; its annual ranges use explicit percentage sensitivities.' : 'Annual scenario ranges are unavailable for this starter.'} Scenario ranges have no assigned probability. Low NPV = Low value − saved derived equity value. Negative modeled cash represents funding needs; applying a higher discount rate to those payments can increase their present value contribution.</p>
      {valuation.hasSignedCash && <p>Signed cash is present: scaling the cash path also scales negative cash and modeled funding needs.</p>}
      {valuation.priceBasis && <><h4>Saved equity-value derivation</h4><dl><dt>Reported-share proxy</dt><dd>{researchNumber(valuation.priceBasis.shares, 6)} million shares</dd><dt>Saved close</dt><dd>{researchNumber(valuation.priceBasis.close, 6)} {valuation.priceBasis.currency ?? 'currency unavailable'} per share</dd><dt>Conversion used</dt><dd>{valuation.priceBasis.method === 'sek' ? `${researchNumber(valuation.priceBasis.fxRate, 8)} SEK per ${valuation.priceBasis.currency ?? 'quote currency'} · FX dated ${valuation.priceBasis.fxDate ?? 'unavailable'}` : `Matching ${valuation.currency} local market value; no additional FX conversion`}</dd></dl><p>Derived equity value = reported shares in millions × saved close{valuation.priceBasis.method === 'sek' ? ' × the observed conversion to SEK' : ''}. Report ended {valuation.priceBasis.reportEnd}, published {valuation.priceBasis.reportDate ?? 'date unavailable'}, source saved {valuation.priceBasis.sourceAsOf}. Source {valuation.priceBasis.sourceId}. Reconcile share classes, splits and ownership claims before interpreting the comparison. The derived equity value is not an observed per-share quote or a sum across share classes.</p></>}
      <p>The 30% margin is a stated purchase policy, not an estimated loss probability. Edit assumptions and the margin in the working valuation.</p>
    </div>}
    <details className="research-gauge-method"><summary>Source versions and research boundaries</summary><PeriodDetails period={annual.latest} label="Latest retained annual report" /><p>Screen calculated {data.asOf}; listing identity saved {row.sourceAsOf}. {row.presence === 'older' ? 'This listing was present only in an older download; that alone does not establish listing status.' : 'This listing is present in the newest bundled directory download.'}</p><p>Saved-vintage observations may include restatements. This screen does not reconstruct an investor’s historical information set, establish a moat, or validate a forecasting model. Provider FCF is not verified cash distributable to common shareholders. Download dates do not make old financial periods or quotes current.</p><p className="hash">Financial pack: {data.financialPackId}<br />Company history SHA-256: {row.sourceCompanySha256}<br />Directory SHA-256: {data.taxonomySha256}<br />Screen model: {data.model}<br />Cash calibration: {data.calibrationId}</p></details>
  </div>;
}

export default function ResearchGaugeCard({ row, data, ready, error, onExplore, onValuation }: {
  row: ResearchGaugeRow | null; data: ResearchGaugeArtifact | null; ready: boolean; error: string; onExplore: () => void; onValuation: () => void;
}) {
  return <section className="research-gauge-card" data-research-card={row?.id ?? ''} data-research-readiness={row?.readiness ?? ''} data-research-route={row?.route ?? ''} data-research-card-ready={ready && !!row && !!data && !error}>
    <h3><ClipboardList size={16} /> Research gauge</h3>
    {!ready ? <p role="status">Opening the saved universe research screen…</p> : error ? <p role="alert">{error}</p> : !row || !data ? <p>No matching research screen is available for this data release.</p> : <>
      <p>{researchRouteLabels[row.route]} · {researchReadinessLabels[row.readiness]}<br />{row.annual.periods.length ? `${row.annual.periods.length} comparable annual periods through ${row.annual.periods[0].end}` : 'No comparable annual window'} · screen {data.asOf}</p>
      <div className="research-gauge-card-metrics"><div><small>Provider FCF observations</small><strong>{researchPositive(row.annual.cash)}</strong></div><div><small>EBIT observations</small><strong>{researchPositive(row.annual.ebit)}</strong></div></div>
      <ul className="research-gauge-reasons">{researchQuestions(row).slice(0, 2).map(question => <li key={question}>{question}</li>)}</ul>
      <p>Historical evidence helps choose what to investigate. It does not establish investment quality or a purchase recommendation.</p>
      <details><summary>Inspect figures, dates and starter valuation</summary><ResearchGaugeEvidence row={row} data={data} showValuation /></details>
    </>}
    <div className="research-gauge-actions"><button onClick={onExplore} aria-label="Explore universe research screen">Explore research screen <ArrowRight size={14} /></button>{ready && row && data && !error && <button onClick={onValuation}>Open working valuation <ArrowRight size={14} /></button>}</div>
  </section>;
}
