import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Download, Save } from 'lucide-react';
import type { CompanyEntry } from './listingCatalogue';
import type { FinancialCompany, FinancialIndex } from './financialData';
import type { ResearchRelease } from './types';
import { format } from './model';
import { blankValuation, calculateValuation, capitalLabels, generateCashFlows, scenarioColors, scenarioKeys, scenarioNames, type Payback, type Scenario, type ScenarioKey, type ValuationDraft } from './valuation';
import { compatibleValuation, loadValuationDraft, loadValuations, saveValuation, saveValuationDraft, type SavedValuation } from './savedValuations';
import ValuationCharts from './ValuationCharts';
import ValuationResearchEvidence from './ValuationResearchEvidence';
import { buildResearchedValuation, shouldStartResearchedStudy, type ResearchedStudy } from './researchedValuations';
import './valuation.css';

const noteLabels: Record<keyof ValuationDraft['notes'], string> = { business: 'Business, competition and moat', macro: 'Macro and branch evidence → company exposure → forecast assumption', financing: 'Capital dates, reinvestment, debt and refinancing', recovery: 'Recovery assets, claims, costs, timing and feasibility', decision: 'Investment thesis, realization path and invalidating evidence' };
const paybackLabel = (p: Payback, years: number) => p.year === null ? `Not reached in ${years} years` : `Year ${p.year}${p.reversed ? ' · reverses later' : ''}`;
function NumberInput({ label, value, onChange, min, max, step = 'any' }: { label: string; value: number | null; onChange: (n: number | null) => void; min?: number; max?: number; step?: string }) {
  return <input type="number" aria-label={label} value={value ?? ''} min={min} max={max} step={step} onChange={e => onChange(e.target.value === '' || !Number.isFinite(e.target.valueAsNumber) ? null : e.target.valueAsNumber)} />;
}
export default function ValuationWorkspace({ entry, financial, history, release, researched, onProfile }: { entry: CompanyEntry; financial: FinancialIndex | null; history: FinancialCompany | null; release: ResearchRelease; researched: ResearchedStudy | null; onProfile: () => void }) {
  const basis = { company: entry.id, release: release.id, financial: financial?.id ?? null, taxonomy: release.taxonomy_sha256 ?? null };
  const startingStudy = useMemo(() => researched ? buildResearchedValuation(researched).draft : null, [researched]);
  const [initial] = useState(() => {
    try {
      const previous = loadValuationDraft(localStorage, basis);
      if (startingStudy && shouldStartResearchedStudy(previous?.draft ?? null)) {
        const draft = structuredClone(startingStudy);
        if (previous?.draft.investment != null && previous.draft.investment > 0) draft.investment = previous.draft.investment;
        return { draft, previous: previous ? { ...previous, id: crypto.randomUUID() } : null, error: '', loaded: true };
      }
      return { draft: previous?.draft ?? blankValuation(entry.display_name), previous: null, error: '', loaded: false };
    }
    catch (e) { return { draft: blankValuation(entry.display_name), previous: null, error: `The previous draft could not open: ${String(e)}`, loaded: false }; }
  });
  const [d, setDraft] = useState<ValuationDraft>(initial.draft), [saved, setSaved] = useState<SavedValuation[]>([]);
  const [message, setMessage] = useState(initial.loaded ? `Researched ${entry.display_name} scenarios loaded automatically.${initial.previous ? ' Your previous draft is retained in saved studies below.' : ''}` : ''), [saveError, setSaveError] = useState(initial.error), [autoSaved, setAutoSaved] = useState(false);
  const [sale, setSale] = useState(false), [tab, setTab] = useState<'scenarios' | 'evidence'>('scenarios');
  const [showInputs, setShowInputs] = useState(!calculateValuation(initial.draft).ready);
  const [generator, setGenerator] = useState<{ scenario: ScenarioKey; first: number | null; growth: number | null }>({ scenario: 'mid', first: null, growth: null });
  const result = useMemo(() => calculateValuation(d), [d]);
  const makeStudy = (): SavedValuation => ({ format: 'macro-atlas-valuation', version: 1, id: crypto.randomUUID(), created: new Date().toISOString(), ...basis, draft: d });
  useEffect(() => { try { setSaved(loadValuations(localStorage)); } catch (e) { setSaveError(String(e)); } }, []);
  useEffect(() => {
    if (initial.error) return;
    try {
      if (initial.previous && !loadValuations(localStorage).some(v => v.id === initial.previous!.id)) {
        saveValuation(localStorage, initial.previous); setSaved(loadValuations(localStorage));
      }
      saveValuationDraft(localStorage, makeStudy()); setAutoSaved(true); setSaveError('');
    }
    catch (e) { setAutoSaved(false); setSaveError(`Draft not saved: ${String(e)}`); }
  }, [d]);
  const update = (patch: Partial<ValuationDraft>) => { setMessage(''); setAutoSaved(false); setDraft(previous => ({ ...previous, ...patch })); };
  const scenario = (key: ScenarioKey, patch: Partial<Scenario>) => update({ scenarios: { ...d.scenarios, [key]: { ...d.scenarios[key], ...patch } } });
  const changeYears = (years: number | null) => {
    if (years === null || !Number.isInteger(years) || years < 1 || years > 50) return;
    update({ years, scenarios: Object.fromEntries(scenarioKeys.map(k => [k, { ...d.scenarios[k], cashFlows: Array.from({ length: Math.max(years, d.scenarios[k].cashFlows.length) }, (_, i) => d.scenarios[k].cashFlows[i] ?? null) }])) as ValuationDraft['scenarios'] });
  };
  const save = () => { try { saveValuation(localStorage, makeStudy()); setSaved(loadValuations(localStorage)); setSaveError(''); setMessage('Study revision saved with these company and data versions.'); } catch (e) { setSaveError(String(e)); } };
  const useResearchedStudy = () => {
    if (!startingStudy) return;
    try {
      saveValuation(localStorage, makeStudy()); setSaved(loadValuations(localStorage));
      const draft = structuredClone(startingStudy); if (d.investment != null && d.investment > 0) draft.investment = d.investment;
      setDraft(draft); setAutoSaved(false); setShowInputs(false); setTab('scenarios'); setSaveError('');
      setMessage('Researched scenarios opened. Your preceding working draft is retained as a saved revision.');
    } catch (e) { setSaveError(`Could not preserve the current draft: ${String(e)}`); }
  };
  const changedFromResearch = startingStudy ? JSON.stringify({ ...d, investment: 1000, title: '', researchAutofillDisabled: false }) !== JSON.stringify({ ...startingStudy, investment: 1000, title: '', researchAutofillDisabled: false }) : false;
  const latestMarket = history?.market.filter(m => m.sek !== null && m.price_date).sort((a, b) => a.price_date!.localeCompare(b.price_date!)).at(-1);
  const latestReport = history?.annual.at(-1);
  const scale = d.marketCap && d.investment ? d.investment / d.marketCap : null;
  const money = (amount: number | null | undefined, stake = false) => amount == null || stake && scale === null ? 'Unavailable' : `${format(stake ? amount * scale! : amount, 2)} ${d.currency}${stake ? '' : ' m'}`;
  const useHistoricalPrice = () => { if (!latestMarket?.price_date || latestMarket.sek === null) return; update({ marketCap: latestMarket.sek, priceDate: latestMarket.price_date, priceSource: `Saved Börsdata publication-window valuation; ${latestMarket.source_id}; price ${latestMarket.price_date}; reported shares ${latestMarket.shares} million; close ${latestMarket.price} ${latestMarket.currency}; FX ${latestMarket.fx_rate} (${latestMarket.fx_date}). Verify issuer/share-class basis.` }); };
  const exportCSV = async () => {
    try {
      if (!result.ready) throw new Error('Complete all three scenarios before exporting calculations.');
      const rows: (string | number | null)[][] = [['company_id', 'study', 'valuation_date', 'price_date', 'currency', 'market_cap_m', 'investment', 'scenario', 'year', 'equity_cash_payment_m', 'discounted_payment_m', 'cumulative_npv_m', 'cumulative_npv_with_sale_m', 'required_equity_return_pct', 'final_equity_sale_m', 'research_version', 'financial_version', 'price_source', 'starting_valuation_study', 'starting_study_date', 'edited_from_starting_study']];
      for (const key of scenarioKeys) for (let i = 0; i <= d.years; i++) rows.push([entry.id, d.title, d.valuationDate, d.priceDate, d.currency, d.marketCap, d.investment, key, i, i ? d.scenarios[key].cashFlows[i - 1] : -d.marketCap!, i ? result.scenarios[key].discounted[i - 1] : -d.marketCap!, result.scenarios[key].cumulativeNPV[i], result.scenarios[key].cumulativeNPVWithSale[i], d.scenarios[key].discountRate, i === d.years ? d.scenarios[key].terminalEquity : 0, release.id, financial?.id ?? '', d.priceSource, d.researchOrigin?.id ?? '', d.researchOrigin?.asOf ?? '', d.researchOrigin ? String(changedFromResearch) : '']);
      const csv = rows.map(row => row.map(v => typeof v === 'number' ? String(v) : `"${String(v ?? '').replace(/^[=+@\-\t\r]/, "'$&").replaceAll('"', '""')}"`).join(',')).join('\r\n');
      const filename = `Macro-Atlas-Valuation-${entry.id}-${d.valuationDate}.csv`;
      if ('__TAURI_INTERNALS__' in window) { const { invoke } = await import('@tauri-apps/api/core'); setMessage(`Saved to ${await invoke<string>('export_csv', { filename, contents: csv })}`); }
      else { const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setMessage('Forecast calculations exported as CSV.'); }
    } catch (e) { setSaveError(String(e)); }
  };
  return <main className="valuation-workspace" data-valuation-company={entry.id} data-valuation-ready={result.ready} data-valuation-study={d.researchOrigin?.id ?? ''}>
    <header className="valuation-heading"><div><button className="valuation-back" onClick={onProfile}><ArrowLeft size={15} />Company profile</button><div className="eyebrow">COMPANIES · VALUE & PRICE</div><h1>{entry.display_name}</h1><p>Three possible paths from your purchase price to shareholder cash.</p></div>
      <div className="valuation-actions"><button aria-expanded={showInputs} onClick={() => { setShowInputs(v => !v); setTab('scenarios'); }}>{showInputs ? 'Hide input forms' : 'Edit price & assumptions'}</button><button onClick={save}><Save size={15} />Save study revision</button><button onClick={exportCSV} disabled={!result.ready}><Download size={15} />Export calculations</button><small>{autoSaved ? 'Working draft saved on this device' : 'Working draft not saved'}</small></div></header>
    {saveError && <p role="alert" className="valuation-alert">{saveError}</p>}{message && <p role="status" className="valuation-status">{message}</p>}
    {researched && <section className="valuation-research-banner"><div><div className="eyebrow">RESEARCHED VALUATION · {researched.asOf}</div><strong>{d.researchOrigin?.id === researched.id ? changedFromResearch ? 'Your edited Holmen study' : 'Holmen scenarios are ready' : 'A researched Holmen study is available'}</strong><p>Reported figures and analyst assumptions are included. <button onClick={() => setTab('evidence')}>Inspect sources and calculations</button></p></div><button className="valuation-research-reset" onClick={useResearchedStudy}>Start from researched assumptions</button></section>}
    {!showInputs && <section className="valuation-price-summary"><div><small>EQUITY PURCHASE BASIS</small><strong>{money(d.marketCap)}</strong><span>Price {d.priceDate} · valuation {d.valuationDate}</span></div><div><small>YOUR INVESTMENT</small><strong>{d.investment === null ? 'Unavailable' : `${format(d.investment, 0)} ${d.currency}`}</strong><span>{d.years} forecast years · editable scenarios</span></div><p>{researched && d.researchOrigin && !changedFromResearch ? `Historical ${researched.name} close ${researched.price.close} SEK × ${researched.price.sharesM}m outstanding common shares. B-equivalent equity basis; no live quote.` : d.priceSource}</p></section>}
    <div className="valuation-tabs" role="tablist" aria-label="Valuation sections"><button role="tab" aria-selected={tab === 'scenarios'} onClick={() => setTab('scenarios')}>Value, price & payback</button><button role="tab" aria-selected={tab === 'evidence'} onClick={() => setTab('evidence')}>Business, capital & evidence</button></div>
    {showInputs && <section className="valuation-card"><div className="valuation-basis">
      <label>Study title<input aria-label="Valuation study title" value={d.title} maxLength={160} onChange={e => update({ title: e.target.value })} /></label>
      <label>Valuation date<input aria-label="Valuation date" type="date" value={d.valuationDate} onChange={e => update({ valuationDate: e.target.value })} /></label>
      <label>Currency<input aria-label="Valuation currency" value={d.currency} maxLength={3} onChange={e => update({ currency: e.target.value.toUpperCase() })} /></label>
      <label>Equity market value · {d.currency} m<NumberInput label="Equity market value" value={d.marketCap} min={0} onChange={marketCap => update({ marketCap })} /></label>
      <label>Price date<input aria-label="Valuation price date" type="date" value={d.priceDate} onChange={e => update({ priceDate: e.target.value })} /></label>
      <label>Your investment · {d.currency}<NumberInput label="Valuation investment amount" value={d.investment} min={0} onChange={investment => update({ investment })} /></label>
      <label>Forecast years<NumberInput label="Valuation forecast years" value={d.years} min={1} max={50} step="1" onChange={changeYears} /></label>
    </div><label>Price source, share basis and currency conversion<textarea aria-label="Valuation price source" value={d.priceSource} maxLength={5000} onChange={e => update({ priceSource: e.target.value })} rows={2} /></label>
      {latestMarket && <p className="valuation-source">Saved reference: {format(latestMarket.sek, 2)} SEK m on {latestMarket.price_date}. This is a historical publication-window valuation. <button disabled={d.currency !== 'SEK'} onClick={useHistoricalPrice}>Use this dated SEK price</button></p>}
      {d.priceDate && d.priceDate < d.valuationDate && <p className="valuation-caution">The price predates this valuation. The comparison uses that dated price, not a live quote.</p>}
      <p className="valuation-method">Enter company amounts in millions of the selected currency. The model discounts <strong>cash returned to common shareholders</strong> after reinvestment, interest and other financing obligations. Use negative payments for additional shareholder funding. These are analyst forecasts; saved vendor FCF is not substituted for shareholder cash.</p>
    </section>}
    {tab === 'scenarios' ? <>
      {showInputs && <section className="valuation-card"><h2>High, mid and low assumptions</h2><p>Enter each path, or generate a starting path and edit individual years. Required returns are equity discount rates. Payments occur at year-end.</p>
        <div className="valuation-scenario-grid">{scenarioKeys.map(key => <div className="valuation-scenario" key={key} style={{ borderTopColor: scenarioColors[key] }}><h3>{scenarioNames[key]}</h3><label>Required equity return · %<NumberInput label={`${scenarioNames[key]} required return`} value={d.scenarios[key].discountRate} min={0} max={100} onChange={discountRate => scenario(key, { discountRate })} /></label><label>Final equity sale · {d.currency} m<NumberInput label={`${scenarioNames[key]} final equity sale`} value={d.scenarios[key].terminalEquity} min={0} onChange={terminalEquity => scenario(key, { terminalEquity })} /></label><small>Net sale proceeds at year {d.years}, in addition to that year's cash payment. Zero means no sale.</small><label>Assumptions and evidence<textarea aria-label={`${scenarioNames[key]} assumptions`} value={d.scenarios[key].rationale} maxLength={5000} rows={3} onChange={e => scenario(key, { rationale: e.target.value })} /></label></div>)}</div>
        <details className="valuation-generator"><summary>Generate an editable cash-flow path</summary><div><label>Scenario<select aria-label="Generate valuation scenario" value={generator.scenario} onChange={e => setGenerator({ ...generator, scenario: e.target.value as ScenarioKey })}>{scenarioKeys.map(k => <option value={k} key={k}>{scenarioNames[k]}</option>)}</select></label><label>Year 1 payment · {d.currency} m<NumberInput label="Generated first cash payment" value={generator.first} onChange={first => setGenerator({ ...generator, first })} /></label><label>Annual change · %<NumberInput label="Generated cash payment growth" value={generator.growth} onChange={growth => setGenerator({ ...generator, growth })} /></label><button onClick={() => { try { if (generator.first === null || generator.growth === null) throw new Error('Enter a starting payment and growth assumption.'); scenario(generator.scenario, { cashFlows: generateCashFlows(generator.first, generator.growth, d.years) }); setMessage('Forecast path filled from your assumptions. Review the annual payments.'); } catch (e) { setSaveError(String(e)); } }}>Fill {scenarioNames[generator.scenario]} path</button></div><p>This replaces the selected path. Growth describes cash payments, after the investment required to support them.</p></details>
        <div className="table-scroll valuation-forecast-table"><table><thead><tr><th>Year after valuation</th>{scenarioKeys.map(k => <th key={k}>{scenarioNames[k]} payment · {d.currency} m</th>)}</tr></thead><tbody>{Array.from({ length: d.years }, (_, i) => <tr key={i}><th>Year {i + 1}</th>{scenarioKeys.map(k => <td key={k}><NumberInput label={`${scenarioNames[k]} year ${i + 1} cash payment`} value={d.scenarios[k].cashFlows[i] ?? null} onChange={n => { const cashFlows = [...d.scenarios[k].cashFlows]; cashFlows[i] = n; scenario(k, { cashFlows }); }} /></td>)}</tr>)}</tbody></table></div>
      </section>}
      <section className="valuation-card"><h2>What your {format(d.investment, 0)} {d.currency} could return</h2><p>Value includes the forecast payments and any final sale. Payback from cash payments is reported separately from recovery that depends on selling.</p>
        <div className="valuation-scenario-grid">{scenarioKeys.map(k => { const r = result.scenarios[k]; return <article className="valuation-result" data-scenario={k} key={k} style={{ borderTopColor: scenarioColors[k] }}><h3>{scenarioNames[k]} scenario</h3>{r.error ? <p className="valuation-incomplete">{r.error}</p> : <><small>ESTIMATED PRESENT VALUE</small><strong data-result="value">{money(r.value, true)}</strong><dl><div><dt>NPV after purchase price</dt><dd data-result="npv">{money(r.npv, true)}</dd></div><div><dt>Value / price</dt><dd>{format(r.valuePrice, 2)}×</dd></div><div><dt>Discount to estimated value</dt><dd>{r.discountToValue === null ? 'Unavailable' : `${format(r.discountToValue * 100, 1)}%`}</dd></div><div><dt>Cash-payment payback</dt><dd data-result="payback">{paybackLabel(r.payback, d.years)}</dd></div><div><dt>Discounted payback</dt><dd data-result="discounted-payback">{paybackLabel(r.discountedPayback, d.years)}</dd></div><div><dt>Payback including final sale</dt><dd>{paybackLabel(r.paybackWithSale, d.years)}</dd></div><div><dt>Discounted, including sale</dt><dd>{paybackLabel(r.discountedPaybackWithSale, d.years)}</dd></div></dl><p>Present value from final sale: {money(r.terminalPV, true)}{r.terminalShare !== null ? ` (${format(r.terminalShare * 100, 1)}% of estimated value)` : ''}.</p></>}</article>; })}</div>
        <p className="valuation-method">Payback is the first year-end cumulative cash covers the initial purchase. “Reverses later” means later funding takes it below cost again. No payback is extrapolated beyond {d.years} years, and the low case is not a guaranteed downside bound.</p>
      </section>
      {result.crossing && <p className="valuation-caution">Some named scenario paths cross. Their original labels remain visible; the shaded range follows the actual minimum and maximum.</p>}
      {result.ready ? <ValuationCharts draft={d} results={result.scenarios} sale={sale} onSale={setSale} /> : <div className="valuation-empty">Complete the dated price and all three cash-flow paths to compare their DCF and cumulative NPV curves.</div>}
      <section className="valuation-card"><h2>Liquidation or breakup recovery</h2><p>A separate alternative to continuing the business. Enter net proceeds for common shareholders after all prior claims, taxes, closure costs and cash burn. Support the estimates in Business, capital & evidence.</p><div className="valuation-scenario-grid">{scenarioKeys.map(k => { const r = result.scenarios[k]; return <div className="valuation-scenario" key={k} style={{ borderTopColor: scenarioColors[k] }}><h3>{scenarioNames[k]}</h3><label>Net equity recovery · {d.currency} m<NumberInput label={`${scenarioNames[k]} net equity recovery`} value={d.scenarios[k].recoveryEquity} min={0} onChange={recoveryEquity => scenario(k, { recoveryEquity })} /></label><label>Payment year · 0 = now<NumberInput label={`${scenarioNames[k]} recovery payment year`} value={d.scenarios[k].recoveryYear} min={0} max={50} step="1" onChange={recoveryYear => scenario(k, { recoveryYear })} /></label>{r.recoveryError && <p>{r.recoveryError}</p>}{r.recovery && <p data-recovery={k}>Present value: <strong>{money(r.recovery.value, true)}</strong><br />NPV: {money(r.recovery.npv, true)}<br />Payback: {r.recovery.payback === null ? 'Not reached by this recovery' : `Year ${r.recovery.payback}`}<br />Discounted: {r.recovery.discountedPayback === null ? 'Not reached by this recovery' : `Year ${r.recovery.discountedPayback}`}</p>}</div>; })}</div><p className="valuation-method">Recovery is not added to the going-concern value. It is not a guaranteed price floor; common shareholders may receive zero. This case assumes one net payment and uses each scenario's required equity return.</p></section>
    </> : <>
      {researched && <ValuationResearchEvidence study={researched} edited={changedFromResearch} />}
      <section className="valuation-card"><h2>Tangible capital and financing</h2><p>Enter reconciled company amounts in {d.currency} millions. These explain the business economics and your ownership exposure; the equity cash-flow model already accounts for financing, so these amounts are not added to or deducted from its value again.</p>
        {latestReport && <p className="valuation-source">Available annual reference: {latestReport.start}–{latestReport.end}, reported {latestReport.report_date ?? 'date unavailable'}, {latestReport.currency} m, saved {latestReport.source_as_of}. Figures below require your reconciliation.</p>}
        <div className="valuation-capital-grid">{(Object.keys(capitalLabels) as (keyof typeof capitalLabels)[]).map(k => <label key={k}>{capitalLabels[k]} · {d.currency} m<NumberInput label={capitalLabels[k]} value={d.capital[k]} onChange={n => update({ capital: { ...d.capital, [k]: n } })} />{scale !== null && d.capital[k] !== null && <small>Your investment's exposure: {money(d.capital[k], true)}</small>}</label>)}</div>
        <p>Return on average tangible capital: <strong>{d.capital.averageTCE !== null && d.capital.averageTCE > 0 && d.capital.nopat !== null ? `${format(d.capital.nopat / d.capital.averageTCE * 100, 2)}%` : 'Unavailable'}</strong>. Match normalized annual NOPAT to the same period's average capital. A nonpositive denominator is unsuitable for this ratio.</p><p>Tangible book equity includes cash and is already net of liabilities. Explain required versus surplus cash, restricted balances, leases, maturities and other claims in the notes.</p>
      </section>
      <section className="valuation-card"><h2>Evidence behind the value</h2><p>Record source dates and locations, the company exposure, the transmission into each forecast and what would invalidate it. A listing country or branch assignment alone does not establish an exposure.</p>{(Object.keys(noteLabels) as (keyof ValuationDraft['notes'])[]).map(k => <label key={k}>{noteLabels[k]}<textarea aria-label={noteLabels[k]} value={d.notes[k]} maxLength={10000} rows={5} onChange={e => update({ notes: { ...d.notes, [k]: e.target.value } })} /></label>)}</section>
    </>}
    <section className="valuation-card"><h2>Saved studies for {entry.display_name}</h2><p>Working drafts reopen on this device. Save revisions to preserve earlier assumptions. Each revision retains the company, research release and financial-data versions used.</p><div className="valuation-saved">{saved.filter(v => v.company === entry.id).map(v => { const matches = compatibleValuation(v, basis.company, basis.release, basis.financial, basis.taxonomy); return <div key={v.id}><button disabled={!matches} onClick={() => { const draft = { ...structuredClone(v.draft), researchAutofillDisabled: true }; setDraft(draft); setShowInputs(!calculateValuation(draft).ready); setMessage('Opened saved assumptions with their original dates.'); }}><strong>{v.draft.title}</strong><span>{v.created.slice(0, 10)} · valuation {v.draft.valuationDate} · price {v.draft.priceDate || 'not entered'}</span></button>{!matches && <small>Different data version. Open the matching research and financial data to reuse this study.</small>}</div>; })}{!saved.some(v => v.company === entry.id) && <p>No saved revisions yet.</p>}</div></section>
    <details className="valuation-method"><summary>Model definitions and source versions</summary><p>This workspace uses an equity-distribution DCF: cash actually forecast to reach common shareholders, plus separately assumed net equity sale proceeds. It does not infer FCFF, subtract debt twice, or invent a perpetual-growth terminal value. Use a justified final sale estimate and document its model. Nominal/real assumptions and all currencies must match.</p><p>NPV = present value of modeled cash receipts − equity price. Ordinary payback accumulates undiscounted payments; discounted payback accumulates present values. All payments are at year-end, so payback is reported in whole years without invented within-year timing. Scenario probabilities are not assigned.</p><p>Drafts and saved revisions are stored locally, separately from research packs. CSV exports contain the dated inputs and annual calculations. Review assumptions and evidence before treating a calculated value as an investment conclusion.</p><p className="valuation-hash">Listing {entry.id} · directory snapshot {entry.source_as_of}<br />Research {basis.release}<br />Financial data {basis.financial ?? 'Unavailable'}<br />Taxonomy {basis.taxonomy ?? 'Unavailable'}</p></details>
  </main>;
}
